package com.campestre.clube.backend_application.core.application.memberdata.command;

import com.campestre.clube.backend_application.core.domain.enums.*;

import java.time.LocalDate;

public record SaveMemberDataCommand(
        String cpf,
        byte[] image,
        String imageFormat,
        String username,
        LocalDate birthDate,
        Sex sex,
        String birthCertificate,
        TshirtSize tshirtSize,
        Boolean isBaptized,
        String cellphoneNumber,
        String issuingAuthority,

        String unitName,
        UnitRole unitRole,
        ClassCategory classCategory,
        ClassRole classRole,

        String fatherName,
        String fatherCellphoneNumber,
        String fatherEmail,
        String motherName,
        String motherCellphoneNumber,
        String motherEmail,
        String responsibleName,
        String responsibleCellphoneNumber,
        String responsibleEmail,

        String addressStreet,
        String addressHouseNumber,
        String addressDistrict,
        String addressState,
        String addressCity,
        String addressCepNumber,
        String addressReferenceHouse,
        String addressComplement,

        String cns,
        String agreement,
        String bloodType,

        Boolean catapora,
        Boolean meningite,
        Boolean hepatite,
        Boolean dengue,
        Boolean pneumonia,
        Boolean malaria,
        Boolean febreAmarela,
        Boolean sarampo,
        Boolean tetano,
        Boolean variola,
        Boolean coqueluche,
        Boolean difteria,
        Boolean rinite,
        Boolean bronquite,
        Boolean asma,
        Boolean rubeola,
        Boolean colera,
        Boolean covid19,
        Boolean h1n1,
        Boolean caxumba,

        String others,
        String heartProblems,
        String drugAllergy,
        Boolean lactoseAllergy,
        String deficiency,
        Boolean bloodTransfusion,
        Boolean haveSkinAllergy,
        String skinAllergyMedication,
        Boolean haveFaintingOrConvulsion,
        String faintingOrConvulsionMedication,
        String psychologicalDisorder,
        Boolean haveAllergy,
        String allergyMedication,
        Boolean haveDiabetic,
        String diabeticMedication,
        Boolean recentSeriousInjury,
        String recentFracture,
        String surgeries,
        String hospitalizationReasonLast5Years
){}