spring.application.name=backend-application
server.error.include-message=always
server.error.include-binding-errors=always

# SPRING
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.data.redis.repositories.enabled=false
server.servlet.context-path=/api

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
# Problema com BD, apague o banco ao descomentar a linha abaixo, rode o projeto e depois comente novamente
#spring.jpa.hibernate.ddl-auto=create-drop

# SECURITY
jasypt.encryptor.password=${ENCRYPT_PASSWORD}
# validade do token em milissegundos (3.600.000 = 1 hora)
jwt.validity=${JWT_VALIDITY}
# palavra passe do token (segredo) necessita de no minimo 32 caracteres
jwt.secret=${JWT_SECRET}

# RABBITMQ
spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=${RABBIT_PORT}
spring.rabbitmq.username=${RABBIT_USER}
spring.rabbitmq.password=${RABBIT_PASSWORD}
rabbitmq.queuename.resetpassword=${RABBIT_RESET_QUEUE}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.cache.type=${REDIS_TYPE}
spring.cache.redis.time-to-live=${REDIS_TTL}
spring.cache.redis.cache-null-values=${REDIS_CACHE_NULL}
spring.cache.redis.key-prefix=${REDIS_PREFIX}